# Generated by Django 5.1.4 on 2025-01-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_route_stop_schedule_routestop_route_stops"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buslocation",
            name="schedule",
        ),
    ]
