# Generated by Django 5.1.4 on 2025-01-09 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_buslocation_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SUB_7_DAYS", "Abònman w ap fini nan 7 jou"),
                            ("SUB_3_DAYS", "Abònman w ap fini nan 3 jou"),
                            ("SUB_1_DAY", "Abònman w ap fini demen"),
                            ("SUB_TODAY", "Abònman w ap fini jodi a"),
                            ("SUB_EXPIRED", "Abònman w fini"),
                            ("BUS_DELAY", "Bus la an reta"),
                            ("BUS_ARRIVAL", "Bus la prèske rive"),
                            ("SYSTEM_UPDATE", "Mizajou sistèm lan"),
                            ("ROUTE_CHANGE", "Chanjman nan wout la"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
